displayName=Intelligence Gathering
author=TzJake-Jad
description=Finds the current Shayzien organised crime meeting and points you to it
tags=intelligence,organised,crime,shayzien,gang
version=1.0.0
plugins=com.tzjakejad.intelligencegathering.IntelligenceGatheringPlugin
build=standard
