displayName=Intelligence Gathering
author=TzJake-Jad
description=Finds the current Shayzien organised crime meeting and points you to it
tags=intelligence,organised,crime,shayzien,gang
plugins=com.tzjakejad.intelligencegathering.IntelligenceGatheringPlugin
